# Generated by Django 4.2.3 on 2023-07-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_createuser_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='createuser',
            name='role',
            field=models.CharField(default='none', max_length=15),
        ),
        migrations.DeleteModel(
            name='UserSignUp',
        ),
    ]
