# Generated by Django 4.2.3 on 2023-07-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_createuser_role_delete_usersignup'),
    ]

    operations = [
        migrations.CreateModel(
            name='docuModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdfFile', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
