# Generated by Django 4.2.3 on 2023-07-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_documodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobName', models.CharField(max_length=150)),
            ],
        ),
    ]
