# Generated by Django 4.2.3 on 2023-08-01 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_jobroles'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=1000)),
                ('isStudent', models.BooleanField(default=False)),
                ('schoolname', models.CharField(max_length=150)),
                ('joinedYear', models.PositiveSmallIntegerField()),
                ('graduationYear', models.SmallIntegerField()),
                ('jobTitle', models.CharField(max_length=150)),
                ('companyName', models.CharField(max_length=150)),
                ('experience', models.PositiveSmallIntegerField()),
                ('resumeFile', models.FileField(upload_to='documents/')),
                ('websiteURL', models.URLField()),
                ('linkedinURL', models.URLField()),
                ('githubURL', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.createuser')),
            ],
        ),
    ]
