# Generated by Django 4.2.3 on 2023-08-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='experience',
            field=models.CharField(max_length=15),
        ),
    ]
