# Generated by Django 4.2.3 on 2023-08-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_userprofile_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='createuser',
            name='completedProfile',
            field=models.BooleanField(default=False),
        ),
    ]
